Persist the uv python install location to workspace
Circle complained about this error

```
error: Failed to inspect Python interpreter from active virtual environment at `/usr/local/share/virtualenvs/tap-google-ads/bin/python3`
  Caused by: Broken symlink at `/usr/local/share/virtualenvs/tap-google-ads/bin/python3`, was the underlying Python interpreter removed?

hint: Consider recreating the environment (e.g., with `uv venv`)

Exited with code exit status 2
```

We hopped up to the container and saw this broken link

```
root@75353d3fa08a:~# ls -l /usr/local/share/virtualenvs/tap-google-ads/bin/python
lrwxrwxrwx 1 root root 76 Aug 13 14:25 /usr/local/share/virtualenvs/tap-google-ads/bin/python -> /root/.local/share/uv/python/cpython-3.11.13-linux-x86_64-gnu/bin/python3.11
```

Co-authored-by: Ben Allred <ben.allred@qlik.com>
Co-authored-by: Dylan Sprayberry <dylan.sprayberry@qlik.com>