SAC-28234: Use `uv` (#102)
* Use uv

Co-authored-by: Ben Allred <ben.allred@qlik.com>
Co-authored-by: Dylan Sprayberry <dylan.sprayberry@qlik.com>

* Turn off integration tests

Co-authored-by: Ben Allred <ben.allred@qlik.com>
Co-authored-by: Dylan Sprayberry <dylan.sprayberry@qlik.com>

* Persist the uv python install location to workspace

Circle complained about this error

```
error: Failed to inspect Python interpreter from active virtual environment at `/usr/local/share/virtualenvs/tap-google-ads/bin/python3`
  Caused by: Broken symlink at `/usr/local/share/virtualenvs/tap-google-ads/bin/python3`, was the underlying Python interpreter removed?

hint: Consider recreating the environment (e.g., with `uv venv`)

Exited with code exit status 2
```

We hopped up to the container and saw this broken link

```
root@75353d3fa08a:~# ls -l /usr/local/share/virtualenvs/tap-google-ads/bin/python
lrwxrwxrwx 1 root root 76 Aug 13 14:25 /usr/local/share/virtualenvs/tap-google-ads/bin/python -> /root/.local/share/uv/python/cpython-3.11.13-linux-x86_64-gnu/bin/python3.11
```

Co-authored-by: Ben Allred <ben.allred@qlik.com>
Co-authored-by: Dylan Sprayberry <dylan.sprayberry@qlik.com>

* Persist python standard lib

Co-authored-by: Ben Allred <ben.allred@qlik.com>
Co-authored-by: Dylan Sprayberry <dylan.sprayberry@qlik.com>

* Use one persist with very specific paths

Multiple `attach_workspace`s seemed to put all of the persisted paths
at every `at:` location. So attaching at `/` should just work the way
we expect it to

Co-authored-by: Ben Allred <ben.allred@qlik.com>
Co-authored-by: Dylan Sprayberry <dylan.sprayberry@qlik.com>

* Move awscli into  set up step so that integration tests can use it too

Co-authored-by: Ben Allred <ben.allred@qlik.com>
Co-authored-by: Dylan Sprayberry <dylan.sprayberry@qlik.com>

* finish converting to uv

Co-authored-by: Ben Allred <ben.allred@qlik.com>
Co-authored-by: Dylan Sprayberry <dylan.sprayberry@qlik.com>

* Let integration tests run again

Co-authored-by: Ben Allred <ben.allred@qlik.com>
Co-authored-by: Dylan Sprayberry <dylan.sprayberry@qlik.com>

* Persist a higher level dir

Co-authored-by: Ben Allred <ben.allred@qlik.com>
Co-authored-by: Dylan Sprayberry <dylan.sprayberry@qlik.com>

---------

Co-authored-by: Ben Allred <ben.allred@qlik.com>
Co-authored-by: Dylan Sprayberry <dylan.sprayberry@qlik.com>